# Generated by Django 5.1.1 on 2024-09-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='till_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
